version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: dt_teste_soffia
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: dt_teste_soffia
      MYSQL_USER: soffia
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: