version: '3.9'

services:

  mysql:
    image: mysql:8.0
    container_name: soffia-testDb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testDB
      MYSQL_USER: soffia
      MYSQL_PASSWORD: soffiaPassword
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: