name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
        env:
          MYSQL_ROOT_PASSWORD: root

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1.2'

    - name: Copy .env file
      run: cp .env.example .env

    - name: Set environment variables
      env:
        DB_CONNECTION: ${{ secrets.DB_CONNECTION }}
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_PORT: ${{ secrets.DB_PORT }}
        DB_DATABASE: ${{ secrets.DB_DATABASE }}
        DB_USERNAME: ${{ secrets.DB_USERNAME }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      run: |
        echo "DB_CONNECTION=${DB_CONNECTION}" >> .env
        echo "DB_HOST=${DB_HOST}" >> .env
        echo "DB_PORT=${DB_PORT}" >> .env
        echo "DB_DATABASE=${DB_DATABASE}" >> .env
        echo "DB_USERNAME=${DB_USERNAME}" >> .env
        echo "DB_PASSWORD=${DB_PASSWORD}" >> .env

    - name: Update composer
      run: composer update

    - name: Install dependencies
      run: composer install

    - name: Generate application key
      run: php artisan key:generate

    - name: Clear and cache configuration
      run: |
        php artisan config:clear
        php artisan config:cache

    - name: Run migration
      run: php artisan migrate --force

    - name: Run tests
      run: php artisan test

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Heroku CLI
      run: curl https://cli-assets.heroku.com/install.sh | sh

    - name: Authenticate with Heroku
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: |
        echo "$HEROKU_API_KEY" | heroku auth:token

    - name: Add Heroku remote
      run: heroku git:remote -a ${{ secrets.HEROKU_APP_NAME }}

    - name: Deploy to Heroku
      run: git push heroku main
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
